version: '3.8'

services:
  ollama:
    image: ollama/ollama
    platform: linux/arm64
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - LANG=C.UTF-8
    restart: unless-stopped

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama

#  stable-diffusion:
#    image: stabilityai/stable-diffusion
#    container_name: stable-diffusion
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./stable-diffusion-data:/data
#    environment:
#      - REPLICATE_API_KEY=your_api_key  # 必要ならAPIキー（お試し用には不要）
#    restart: unless-stopped

